### ISSUE TITLE
你这个项目怎么热部署

### ISSUE THREAD

**Issue by liudianpeng** [whoismy8023/SPPanAdmin#2]
我修改了html页面,还需要重新跑项目,浏览器才能生效,如何实现热部署呢?我查了一下但是不好使,可以指教一下吗

**Comment by whoismy8023** [comment]
配置方式见[idea实现springboot热加载](http://whoismy8023.gitee.io/2018/01/10/idea%E5%AE%9E%E7%8E%B0springboot%E7%83%AD%E5%8A%A0%E8%BD%BD/)

**Comment by AllExample** [comment]
好的 谢谢
