### ISSUE TITLE
集成shiroTags标签-不管用

### ISSUE THREAD

**Issue by luomouren** [whoismy8023/SPPanAdmin#3]
使用demo，后台数据库删除部分权限，前台菜单栏没有根据权限隐藏，仍显示所有的菜单了。
FreeMarkerConfig 修改如下，不使用自己的标签。maven pom文件添加引用
 <dependency>
            <groupId>net.mingsoft</groupId>
            <artifactId>shiro-freemarker-tags</artifactId>
            <version>0.1</version>
        </dependency>
配置类修改如下
import com.jagregory.shiro.freemarker.ShiroTags;
import freemarker.template.TemplateModelException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer;

import javax.annotation.PostConstruct;

/**
 * Freemarker + shiro 权限控制标签.集成shiroTags标签
 *
 * @author luomouren
 */
@Component
public class FreeMarkerConfig {
	@Autowired
	private FreeMarkerConfigurer freeMarkerConfigurer;

	@PostConstruct
	public void setSharedVariable() throws TemplateModelException {
		freeMarkerConfigurer.getConfiguration().setSharedVariable("shiro", new ShiroTags());
	}
}

**Comment by whoismy8023** [comment]
问题是出在资源数据的key有问题，已经处理
